config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :posts do
    resources :comments
  end

  get 'about', to: 'static#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :email, :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, :body, presence: true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @post
    else
      redirect_back fallback_location: root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :body).merge(post_id: @post.id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Successfully created post.'
    else
      render :new, alert: 'Sorry, there was a problem saving.'
    end
  end

  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Succesfully updated post.'
    else
      render :edit, alert: 'Sorry, there was a problem updating.'
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: 'Deleted post.'
    else
      redirect_back fallback_location: root_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :body)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice].present? || flash[:error].present? || notice.present? || alert.present? %>
      <div class="notification is-marginless" id="app-notification">
        <button class="delete"></button>
        <%= flash[:notice] || flash[:error] || notice || alert %>
      </div>
    <% end %>

    <div class="main-columns columns is-marginless">
      <aside class="column is-3 menu has-background-light">
        <div class="menu-label">
          Website
        </div>
        <ul class="menu-list">
          <li><%= link_to 'Blog', posts_path %></li>
          <li><%= link_to 'About', about_path %></li>
        </ul>
        <div class="menu-label">
          Social
        </div>
        <ul class="menu-list">
          <li><%= link_to 'Twitter', 'https://twitter.com/@nickjnish' %></li>
          <li><%= link_to 'GitHub', 'https://github.com/nicknish' %></li>
          <li><%= mail_to 'nickjnish@gmail.com', 'Email' %></li>
        </ul>
      </aside>

      <div class="column is-9 is-paddingless">
        <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
          <div class="navbar-menu is-active">
            <div class="navbar-start">
              <% if params[:controller] == 'posts' %>
              <div class="navbar-item">Posts</div>
              <% else %>
                <div class="navbar-item">About</div>
              <% end %>
            </div>
            <div class="navbar-end">
              <% if current_user.present? %>
                <%= link_to 'New Post', new_post_path, class: 'navbar-item' %>
                <%= link_to 'Logout', destroy_user_session_path, class: 'navbar-item', method: :delete %>
              <% end %>
            </div>
          </div>
        </nav>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<main class="content p-lg">
  <h1 class="title is-2">Edit Post</h1>

  <%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :name, class: 'label' %>
      <div class="control">
        <%= f.text_field :name, class: 'input' %>
      </div>
    </div>

    <div class="field">
      <%= f.label :body, class: 'label' %>
      <div class="control">
        <%= f.text_area :body, class: 'input' %>
      </div>
    </div>

    <%= f.submit 'Update post', class: 'button is-primary' %>
  <% end %>
</main>

app/views/posts/index.html.erb
<main class="p-lg">
  <% @posts.each do |post| %>
    <article class="content m-b-m">
      <div class="m-b-sm">
        <h3 class="title is-3 is-marginless">
          <%= link_to post.name, post %>
        </h3>
        <span class="subtitle is-7">Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
      </div>
      <p><%= post.body %></p>
    </article>
  <% end %>
</main>

app/views/posts/new.html.erb
<main class="content p-lg">
  <h1 class="title is-2">New Post</h1>

  <%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :name, class: 'label' %>
      <div class="control">
        <%= f.text_field :name, class: 'input' %>
      </div>
    </div>

    <div class="field">
      <%= f.label :body, class: 'label' %>
      <div class="control">
        <%= f.text_area :body, class: 'input' %>
      </div>
    </div>

    <%= f.submit 'Create Post', class: 'button is-primary' %>
  <% end %>
</main>

app/views/posts/show.html.erb
<article class="content p-lg p-b-xl">
  <div class="m-b-lg">
    <div class="m-b-md">
      <h1 class="title is-2 is-marginless">
        <%= @post.name %>
      </h1>
      <span class="subtitle is-7">Posted <%= time_ago_in_words(@post.created_at) %> ago.</span>
    </div>

    <% if current_user.present? %>
      <div class="field is-grouped">
        <div class="control">
          <%= link_to 'Edit', edit_post_path(@post), class: 'button' %>
        </div>
        <div class="control">
          <%= link_to 'Delete', @post, class: 'button is-danger', method: :delete %>
        </div>
      </div>
    <% end %>

    <p><%= @post.body %></p>
  </div>

  <div>
    <h3 class="subtitle is-4">
      <%= "#{@comments.size} #{'Comment'.pluralize(@comments.size)}" %>
    </h3>

    <div class="m-b-lg">
      <% @comments.each do |comment| %>
        <div class="message is-marginless">
          <div class="message-body">
            <p class="is-marginless"><%= comment.body %></p>
            <span class="subtitle is-7">Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.name %>.</span>
          </div>
        </div>
      <% end %>
    </div>

    <h4>Add a comment</h4>

    <%= form_for [@post, Comment.new(post: @post)] do |f| %>
      <div class="field">
        <%= f.label :name, class: 'label' %>
        <div class="control">
          <%= f.text_field :name, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <%= f.label :email, class: 'label' %>
        <div class="control">
          <%= f.email_field :email, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <%= f.label :body, class: 'label' %>
        <div class="control">
          <%= f.text_area :body, class: 'input' %>
        </div>
      </div>

      <%= f.submit 'Post comment', class: 'button is-primary' %>
    <% end %>
  </div>
</article>